# Generated by Django 3.2.5 on 2023-07-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
